const data = {
  data: [
    {
      id: 1,
      text: 'Epic 01',
      start_date: null,
      duration: null,
      parent: 0,
      progress: 0,
      status: 'Done',
      open: true,
    },
    {
      id: 2,
      text: 'Task #1',
      start_date: new Date(2019, 1, 1),
      duration: 5,
      parent: 1,
      status: 'Done',
      progress: 1,
    },
    {
      id: 3,
      text: 'Task #2',
      start_date: new Date(2019, 1, 1),
      duration: 2,
      parent: 1,
      status: 'Done',
      progress: 0.5,
    },
    {
      id: 4,
      text: 'Task #3',
      start_date: null,
      duration: null,
      parent: 1,
      progress: 0.8,
      status: 'To do',
      open: true,
    },
    {
      id: 5,
      text: 'Task #3.1',
      start_date: new Date(2019, 1, 1),
      duration: 2,
      parent: 4,
      progress: 0.2,
      status: 'Done',
    },
    {
      id: 6,
      text: 'Task #3.2',
      start_date: new Date(2019, 1, 2),
      duration: 1,
      parent: 4,
      progress: 0,
      status: 'In Progress',
    },
  ],
  // links: [
  //   {id: 1, source: 2, target: 3, type: '0'},
  //   {id: 2, source: 3, target: 4, type: '0'},
  //   {id: 3, source: 5, target: 6, type: '0'},
  // ],
};

export default data;
